apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-policy-json-input
  labels:
    app: test-policy-json-input
    pool: poc-pool-json-input
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 443
      protocol: UDP
  - ports:
    - port: 22
      protocol: TCP
    - port: 22
      protocol: UDP
    to:
    - ipBlock:
        cidr: 10.0.6.11/32
    - ipBlock:
        cidr: 10.0.6.12/32
  podSelector:
    matchLabels:
      app: test-policy-json-input
      pool: poc-pool-json-input
  policyTypes:
  - Ingress
  - Egress